export const foodDB = {
  // ── Пилешко ──────────────────────────────────────────────────────
  'пилешко филе':           { label: 'Пилешко филе',              labelEn: 'Chicken breast',        kcal: 165, protein: 31   },
  'пилешко бутче':          { label: 'Пилешко бутче (с кост)',    labelEn: 'Chicken leg (bone-in)', kcal: 215, protein: 18   },
  'пилешки бутчета':        { label: 'Пилешки бутчета (б/к)',     labelEn: 'Chicken thigh (b/l)',   kcal: 174, protein: 25   },
  'пилешки гърди':          { label: 'Пилешки гърди',             labelEn: 'Chicken breast',        kcal: 165, protein: 31   },
  'пилешко крило':          { label: 'Пилешко крило',             labelEn: 'Chicken wing',          kcal: 203, protein: 18   },
  'пилешки черен дроб':     { label: 'Пилешки черен дроб',        labelEn: 'Chicken liver',         kcal: 116, protein: 17   },
  'пуешко филе':            { label: 'Пуешко филе',               labelEn: 'Turkey breast',         kcal: 135, protein: 29   },

  // ── Телешко ──────────────────────────────────────────────────────
  'телешко бонфиле':        { label: 'Телешко бонфиле',           labelEn: 'Beef tenderloin',       kcal: 187, protein: 27   },
  'телешка кайма':          { label: 'Телешка кайма',             labelEn: 'Ground beef',           kcal: 250, protein: 26   },
  'телешко бедро':          { label: 'Телешко бедро',             labelEn: 'Beef round',            kcal: 158, protein: 24   },
  'телешко рамо':           { label: 'Телешко рамо',              labelEn: 'Beef shoulder',         kcal: 175, protein: 23   },
  'телешко ребро':          { label: 'Телешко ребро',             labelEn: 'Beef ribs',             kcal: 221, protein: 18   },
  'телешки черен дроб':     { label: 'Телешки черен дроб',        labelEn: 'Beef liver',            kcal: 135, protein: 21   },
  'телешка пържола':        { label: 'Телешка пържола',           labelEn: 'Beef steak',            kcal: 271, protein: 24   },

  // ── Свинско ──────────────────────────────────────────────────────
  'свински врат':           { label: 'Свински врат',              labelEn: 'Pork neck',             kcal: 290, protein: 18   },
  'свинско бонфиле':        { label: 'Свинско бонфиле',           labelEn: 'Pork tenderloin',       kcal: 143, protein: 21   },
  'свински котлет':         { label: 'Свински котлет',            labelEn: 'Pork chop',             kcal: 231, protein: 25   },
  'свинска плешка':         { label: 'Свинска плешка',            labelEn: 'Pork shoulder',         kcal: 263, protein: 19   },
  'свинско бедро':          { label: 'Свинско бедро',             labelEn: 'Pork leg',              kcal: 215, protein: 21   },
  'свинско ребро':          { label: 'Свинско ребро',             labelEn: 'Pork ribs',             kcal: 321, protein: 18   },
  'бекон':                  { label: 'Бекон',                     labelEn: 'Bacon',                 kcal: 417, protein: 12   },
  'кайма смес':             { label: 'Кайма смес',                labelEn: 'Mixed ground meat',     kcal: 260, protein: 17   },

  // ── Заешко ───────────────────────────────────────────────────────
  'заешко':                 { label: 'Заешко месо',               labelEn: 'Rabbit meat',           kcal: 173, protein: 21   },
  'заешко бутче':           { label: 'Заешко бутче',              labelEn: 'Rabbit leg',            kcal: 162, protein: 20   },
  'заешко филе':            { label: 'Заешко филе',               labelEn: 'Rabbit fillet',         kcal: 153, protein: 22   },

  // ── Риби ─────────────────────────────────────────────────────────
  'сьомга':                 { label: 'Сьомга',                    labelEn: 'Salmon',                kcal: 206, protein: 22   },
  'пъстърва':               { label: 'Пъстърва',                  labelEn: 'Trout',                 kcal: 141, protein: 20   },
  'треска':                 { label: 'Треска',                    labelEn: 'Cod',                   kcal: 82,  protein: 18   },
  'хек':                    { label: 'Хек',                       labelEn: 'Hake',                  kcal: 90,  protein: 19   },
  'скумрия':                { label: 'Скумрия',                   labelEn: 'Mackerel',              kcal: 205, protein: 19   },
  'херинга':                { label: 'Херинга',                   labelEn: 'Herring',               kcal: 158, protein: 18   },
  'сардини':                { label: 'Сардини',                   labelEn: 'Sardines',              kcal: 208, protein: 25   },
  'лаврак':                 { label: 'Лаврак',                    labelEn: 'Sea bass',              kcal: 124, protein: 23   },
  'ципура':                 { label: 'Ципура',                    labelEn: 'Sea bream',             kcal: 121, protein: 20   },
  'кефал':                  { label: 'Кефал',                     labelEn: 'Mullet',                kcal: 117, protein: 19   },
  'калкан':                 { label: 'Калкан',                    labelEn: 'Turbot',                kcal: 91,  protein: 17   },
  'паламуд':                { label: 'Паламуд',                   labelEn: 'Atlantic bonito',       kcal: 144, protein: 22   },
  'риба меч':               { label: 'Риба меч',                  labelEn: 'Swordfish',             kcal: 121, protein: 20   },
  'тон':                    { label: 'Риба тон',                  labelEn: 'Tuna',                  kcal: 132, protein: 29   },
  'риба тон':               { label: 'Риба тон',                  labelEn: 'Tuna',                  kcal: 132, protein: 29   },
  'скариди':                { label: 'Скариди',                   labelEn: 'Shrimp',                kcal: 99,  protein: 24   },
  'миди':                   { label: 'Миди',                      labelEn: 'Mussels',               kcal: 86,  protein: 12   },
  'октопод':                { label: 'Октопод',                   labelEn: 'Octopus',               kcal: 82,  protein: 15   },
  'калмари':                { label: 'Калмари',                   labelEn: 'Calamari',              kcal: 92,  protein: 16   },

  // ── Яйца ─────────────────────────────────────────────────────────
  'яйца':                   { label: 'Яйца',   labelEn: 'Eggs',         kcal: 155, protein: 13, perPiece: true, gramsPerPiece: 55 },
  'яйце':                   { label: 'Яйце',   labelEn: 'Egg',          kcal: 155, protein: 13, perPiece: true, gramsPerPiece: 55 },
  'белтъци':                { label: 'Белтъци',                   labelEn: 'Egg whites',            kcal: 52,  protein: 11   },

  // ── Млечни ───────────────────────────────────────────────────────
  'сирене':                 { label: 'Сирене',                    labelEn: 'White cheese (feta)',   kcal: 260, protein: 14   },
  'кашкавал':               { label: 'Кашкавал',                  labelEn: 'Yellow cheese',         kcal: 356, protein: 25   },
  'извара':                 { label: 'Извара',                    labelEn: 'Cottage cheese',        kcal: 98,  protein: 11   },
  'кисело мляко':           { label: 'Кисело мляко',              labelEn: 'Yogurt',                kcal: 61,  protein: 3.5  },
  'гръцко кисело мляко':    { label: 'Гръцко кисело мляко',       labelEn: 'Greek yogurt',          kcal: 97,  protein: 9    },
  'моцарела':               { label: 'Моцарела',                  labelEn: 'Mozzarella',            kcal: 280, protein: 22   },
  'пармезан':               { label: 'Пармезан',                  labelEn: 'Parmesan',              kcal: 431, protein: 38   },
  'скир':                   { label: 'Скир',                      labelEn: 'Skyr',                  kcal: 65,  protein: 11   },

  // ── Зърнени и бобови ─────────────────────────────────────────────
  'ориз':                   { label: 'Ориз (сготвен)',             labelEn: 'Rice (cooked)',         kcal: 130, protein: 2.7  },
  'бял ориз':               { label: 'Бял ориз (сготвен)',         labelEn: 'White rice (cooked)',   kcal: 130, protein: 2.7  },
  'кафяв ориз':             { label: 'Кафяв ориз (сготвен)',       labelEn: 'Brown rice (cooked)',   kcal: 123, protein: 2.7  },
  'картофи':                { label: 'Картофи',                   labelEn: 'Potatoes',              kcal: 87,  protein: 1.9  },
  'печени картофи':         { label: 'Печени картофи',            labelEn: 'Baked potatoes',        kcal: 120, protein: 2.5  },
  'сладки картофи':         { label: 'Сладки картофи',            labelEn: 'Sweet potatoes',        kcal: 86,  protein: 1.6  },
  'овес':                   { label: 'Овесени ядки',              labelEn: 'Oats',                  kcal: 370, protein: 13   },
  'хляб':                   { label: 'Хляб',                      labelEn: 'Bread',                 kcal: 265, protein: 9    },
  'бял хляб':               { label: 'Бял хляб',                  labelEn: 'White bread',           kcal: 265, protein: 9    },
  'пълнозърнест хляб':      { label: 'Пълнозърнест хляб',         labelEn: 'Whole grain bread',     kcal: 247, protein: 13   },
  'тортила':                { label: 'Тортила',                   labelEn: 'Tortilla',              kcal: 310, protein: 8    },
  'паста':                  { label: 'Паста (сготвена)',           labelEn: 'Pasta (cooked)',        kcal: 157, protein: 5.8  },
  'спагети':                { label: 'Спагети (сготвени)',         labelEn: 'Spaghetti (cooked)',    kcal: 158, protein: 5.8  },
  'кус-кус':                { label: 'Кус-кус (сготвен)',          labelEn: 'Couscous (cooked)',     kcal: 112, protein: 3.8  },
  'киноа':                  { label: 'Киноа (сготвена)',           labelEn: 'Quinoa (cooked)',       kcal: 120, protein: 4.4  },
  'булгур':                 { label: 'Булгур (сготвен)',           labelEn: 'Bulgur (cooked)',       kcal: 83,  protein: 3.1  },
  'боб':                    { label: 'Боб (сготвен)',              labelEn: 'Beans (cooked)',        kcal: 127, protein: 8.7  },
  'леща':                   { label: 'Леща (сготвена)',            labelEn: 'Lentils (cooked)',      kcal: 116, protein: 9    },
  'нахут':                  { label: 'Нахут (сготвен)',            labelEn: 'Chickpeas (cooked)',    kcal: 164, protein: 8.9  },

  // ── Плодове и зеленчуци ──────────────────────────────────────────
  'банан':                  { label: 'Банан',                     labelEn: 'Banana',                kcal: 89,  protein: 1.1  },
  'ябълка':                 { label: 'Ябълка',                    labelEn: 'Apple',                 kcal: 52,  protein: 0.3  },
  'портокал':               { label: 'Портокал',                  labelEn: 'Orange',                kcal: 47,  protein: 0.9  },
  'авокадо':                { label: 'Авокадо',                   labelEn: 'Avocado',               kcal: 160, protein: 2    },
  'домати':                 { label: 'Домати',                    labelEn: 'Tomatoes',              kcal: 18,  protein: 0.9  },
  'краставица':             { label: 'Краставица',                labelEn: 'Cucumber',              kcal: 15,  protein: 0.7  },
  'броколи':                { label: 'Броколи',                   labelEn: 'Broccoli',              kcal: 35,  protein: 2.8  },
  'моркови':                { label: 'Моркови',                   labelEn: 'Carrots',               kcal: 41,  protein: 0.9  },
  'чушки':                  { label: 'Чушки',                     labelEn: 'Bell peppers',          kcal: 31,  protein: 1    },
  'салата':                 { label: 'Салата',                    labelEn: 'Lettuce',               kcal: 15,  protein: 1.4  },

  // ── Мазнини и масла ──────────────────────────────────────────────
  'зехтин':                 { label: 'Зехтин',                    labelEn: 'Olive oil',             kcal: 884, protein: 0    },
  'олио':                   { label: 'Слънчогледово олио',        labelEn: 'Sunflower oil',         kcal: 884, protein: 0    },
  'слънчогледово олио':     { label: 'Слънчогледово олио',        labelEn: 'Sunflower oil',         kcal: 884, protein: 0    },
  'шарлан':                 { label: 'Шарланово олио',            labelEn: 'Sesame oil',            kcal: 884, protein: 0    },
  'шарланово олио':         { label: 'Шарланово олио',            labelEn: 'Sesame oil',            kcal: 884, protein: 0    },
  'масло':                  { label: 'Краве масло',               labelEn: 'Butter',                kcal: 717, protein: 0.9  },
  'краве масло':            { label: 'Краве масло',               labelEn: 'Butter',                kcal: 717, protein: 0.9  },
  'кокосово масло':         { label: 'Кокосово масло',            labelEn: 'Coconut oil',           kcal: 892, protein: 0    },

  // ── Ядки и семена ────────────────────────────────────────────────
  'ядки':                   { label: 'Ядки',                      labelEn: 'Nuts',                  kcal: 607, protein: 20   },
  'бадеми':                 { label: 'Бадеми',                    labelEn: 'Almonds',               kcal: 579, protein: 21   },
  'орехи':                  { label: 'Орехи',                     labelEn: 'Walnuts',               kcal: 654, protein: 15   },
  'кашу':                   { label: 'Кашу',                      labelEn: 'Cashews',               kcal: 553, protein: 18   },
  'шам фъстък':             { label: 'Шам фъстък',               labelEn: 'Pistachios',            kcal: 562, protein: 20   },
  'фъстъци':                { label: 'Фъстъци',                  labelEn: 'Peanuts',               kcal: 567, protein: 26   },
  'лешници':                { label: 'Лешници',                  labelEn: 'Hazelnuts',             kcal: 628, protein: 15   },
  'макадамия':              { label: 'Макадамия',                 labelEn: 'Macadamia nuts',        kcal: 718, protein: 8    },
  'бразилски орехи':        { label: 'Бразилски орехи',           labelEn: 'Brazil nuts',           kcal: 656, protein: 14   },
  'пеканови орехи':         { label: 'Пеканови орехи',            labelEn: 'Pecans',                kcal: 691, protein: 9    },
  'слънчогледово семе':     { label: 'Слънчогледово семе',        labelEn: 'Sunflower seeds',       kcal: 584, protein: 21   },
  'тиквено семе':           { label: 'Тиквено семе',             labelEn: 'Pumpkin seeds',         kcal: 559, protein: 30   },
  'ленено семе':            { label: 'Ленено семе',              labelEn: 'Flax seeds',            kcal: 534, protein: 18   },
  'чиа семена':             { label: 'Чиа семена',               labelEn: 'Chia seeds',            kcal: 486, protein: 17   },
  'сусам':                  { label: 'Сусам',                    labelEn: 'Sesame seeds',          kcal: 573, protein: 18   },
  'тахан':                  { label: 'Тахан',                    labelEn: 'Tahini',                kcal: 595, protein: 17   },
  'фъстъчено масло':        { label: 'Фъстъчено масло',           labelEn: 'Peanut butter',         kcal: 588, protein: 25   },
  'бадемово масло':         { label: 'Бадемово масло',            labelEn: 'Almond butter',         kcal: 614, protein: 21   },

  // ── Протеин и добавки ──────────────────────────────────────────
  'протеин':                { label: 'Суроватъчен протеин',       labelEn: 'Whey protein',          kcal: 400, protein: 80   },
  'суроватъчен протеин':    { label: 'Суроватъчен протеин',       labelEn: 'Whey protein',          kcal: 400, protein: 80   },
  'казеин':                 { label: 'Казеин протеин',            labelEn: 'Casein protein',        kcal: 370, protein: 75   },
  'веган протеин':          { label: 'Веган протеин',             labelEn: 'Vegan protein',         kcal: 380, protein: 70   },
  'протеинов бар':          { label: 'Протеинов бар',             labelEn: 'Protein bar',           kcal: 350, protein: 20, perPiece: true, gramsPerPiece: 60 },
  'креатин':                { label: 'Креатин',                   labelEn: 'Creatine',              kcal: 0,   protein: 0    },

  // ── Млечни продукти (допълнителни) ─────────────────────────────
  'прясно мляко':           { label: 'Прясно мляко',              labelEn: 'Whole milk',            kcal: 64,  protein: 3.3  },
  'прясно мляко 1.5%':      { label: 'Прясно мляко 1.5%',         labelEn: 'Low-fat milk 1.5%',     kcal: 47,  protein: 3.4  },
  'прясно мляко 3.6%':      { label: 'Прясно мляко 3.6%',         labelEn: 'Whole milk 3.6%',       kcal: 64,  protein: 3.3  },
  'айрян':                  { label: 'Айрян',                     labelEn: 'Ayran',                 kcal: 37,  protein: 1.7  },
  'кефир':                  { label: 'Кефир',                     labelEn: 'Kefir',                 kcal: 56,  protein: 3.3  },
  'сметана':                { label: 'Сметана',                   labelEn: 'Sour cream',            kcal: 193, protein: 2.1  },
  'сметана за готвене':     { label: 'Сметана за готвене',         labelEn: 'Cooking cream',         kcal: 196, protein: 2.5  },
  'крема сирене':           { label: 'Крема сирене',              labelEn: 'Cream cheese',          kcal: 342, protein: 6    },
  'рикота':                 { label: 'Рикота',                    labelEn: 'Ricotta',               kcal: 174, protein: 11   },
  'маскарпоне':             { label: 'Маскарпоне',                labelEn: 'Mascarpone',            kcal: 429, protein: 5    },
  'топено сирене':          { label: 'Топено сирене',             labelEn: 'Processed cheese',      kcal: 313, protein: 18   },
  'чедър':                  { label: 'Чедър',                     labelEn: 'Cheddar',               kcal: 403, protein: 25   },
  'ементал':                { label: 'Ементал',                   labelEn: 'Emmental',              kcal: 380, protein: 29   },
  'бри':                    { label: 'Бри',                       labelEn: 'Brie',                  kcal: 334, protein: 21   },
  'халуми':                 { label: 'Халуми',                    labelEn: 'Halloumi',              kcal: 321, protein: 25   },

  // ── Скир и пудинги ─────────────────────────────────────────────
  'скир ванилия':           { label: 'Скир ванилия',              labelEn: 'Skyr vanilla',          kcal: 80,  protein: 10   },
  'скир ягода':             { label: 'Скир ягода',                labelEn: 'Skyr strawberry',       kcal: 79,  protein: 10   },
  'скир боровинка':         { label: 'Скир боровинка',            labelEn: 'Skyr blueberry',        kcal: 79,  protein: 10   },
  'скир натурален':         { label: 'Скир натурален',            labelEn: 'Skyr plain',            kcal: 63,  protein: 11   },
  'пудинг шоколад':         { label: 'Пудинг шоколад',            labelEn: 'Chocolate pudding',     kcal: 120, protein: 3    },
  'пудинг ванилия':         { label: 'Пудинг ванилия',            labelEn: 'Vanilla pudding',       kcal: 110, protein: 2.8  },
  'протеинов пудинг':       { label: 'Протеинов пудинг',          labelEn: 'Protein pudding',       kcal: 90,  protein: 15   },
  'кондензирано мляко':     { label: 'Кондензирано мляко',        labelEn: 'Condensed milk',        kcal: 321, protein: 8    },

  // ── Пакетирани храни и снакове ─────────────────────────────────
  'шоколад млечен':         { label: 'Шоколад млечен',            labelEn: 'Milk chocolate',        kcal: 535, protein: 8    },
  'шоколад тъмен':          { label: 'Шоколад тъмен',             labelEn: 'Dark chocolate',        kcal: 546, protein: 5    },
  'шоколад бял':            { label: 'Шоколад бял',               labelEn: 'White chocolate',       kcal: 539, protein: 6    },
  'бисквити':               { label: 'Бисквити',                  labelEn: 'Biscuits',              kcal: 480, protein: 6    },
  'вафла':                  { label: 'Вафла',                     labelEn: 'Wafer',                 kcal: 530, protein: 5, perPiece: true, gramsPerPiece: 33 },
  'кроасан':                { label: 'Кроасан',                   labelEn: 'Croissant',             kcal: 406, protein: 8, perPiece: true, gramsPerPiece: 60 },
  'кроасан шоколад':        { label: 'Кроасан с шоколад',         labelEn: 'Chocolate croissant',   kcal: 430, protein: 7, perPiece: true, gramsPerPiece: 70 },
  'чипс':                   { label: 'Чипс',                     labelEn: 'Chips / Crisps',        kcal: 536, protein: 7    },
  'пуканки':                { label: 'Пуканки',                   labelEn: 'Popcorn',               kcal: 375, protein: 11   },
  'крекери':                { label: 'Крекери',                   labelEn: 'Crackers',              kcal: 492, protein: 10   },
  'солети':                 { label: 'Солети',                    labelEn: 'Pretzels',              kcal: 380, protein: 10   },
  'гевреци':                { label: 'Гевреци',                   labelEn: 'Bagel pretzels',        kcal: 370, protein: 10   },
  'мюсли бар':              { label: 'Мюсли бар',                 labelEn: 'Granola bar',           kcal: 440, protein: 8, perPiece: true, gramsPerPiece: 35 },
  'оризови бисквити':       { label: 'Оризови бисквити',          labelEn: 'Rice cakes',            kcal: 387, protein: 8    },
  'корн флейкс':            { label: 'Корн флейкс',               labelEn: 'Corn flakes',           kcal: 357, protein: 7    },
  'мюсли':                  { label: 'Мюсли',                     labelEn: 'Muesli',                kcal: 370, protein: 10   },
  'гранола':                { label: 'Гранола',                   labelEn: 'Granola',               kcal: 450, protein: 10   },
  'нутела':                 { label: 'Нутела',                    labelEn: 'Nutella',               kcal: 539, protein: 6    },
  'мармалад':               { label: 'Мармалад / Конфитюр',       labelEn: 'Jam',                   kcal: 250, protein: 0.4  },
  'мед':                    { label: 'Мед',                       labelEn: 'Honey',                 kcal: 304, protein: 0.3  },
  'локум':                  { label: 'Локум',                     labelEn: 'Turkish delight',       kcal: 350, protein: 0.5  },
  'халва':                  { label: 'Халва',                     labelEn: 'Halva',                 kcal: 469, protein: 12   },
  'баклава':                { label: 'Баклава',                   labelEn: 'Baklava',               kcal: 430, protein: 6, perPiece: true, gramsPerPiece: 80 },
  'сладолед':               { label: 'Сладолед',                  labelEn: 'Ice cream',             kcal: 207, protein: 3.5  },
  'сладолед протеинов':     { label: 'Сладолед протеинов',        labelEn: 'Protein ice cream',     kcal: 120, protein: 10   },

  // ── Хляб и тестени ─────────────────────────────────────────────
  'ръжен хляб':             { label: 'Ръжен хляб',                labelEn: 'Rye bread',             kcal: 259, protein: 9    },
  'питка':                  { label: 'Питка',                     labelEn: 'Flatbread',             kcal: 275, protein: 8, perPiece: true, gramsPerPiece: 80 },
  'лаваш':                  { label: 'Лаваш',                    labelEn: 'Lavash',                kcal: 275, protein: 9    },
  'фокача':                 { label: 'Фокача',                    labelEn: 'Focaccia',              kcal: 271, protein: 8    },
  'пица тесто':             { label: 'Пица тесто',               labelEn: 'Pizza dough',           kcal: 266, protein: 8    },
  'блат за пица':           { label: 'Блат за пица',              labelEn: 'Pizza base',            kcal: 266, protein: 8    },
  'палачинка':              { label: 'Палачинка',                 labelEn: 'Pancake/Crepe',         kcal: 227, protein: 7, perPiece: true, gramsPerPiece: 50 },
  'банички':                { label: 'Баничка',                   labelEn: 'Banitsa (cheese pastry)',kcal: 280, protein: 8, perPiece: true, gramsPerPiece: 100 },

  // ── Плодове (допълнителни) ─────────────────────────────────────
  'грозде':                 { label: 'Грозде',                    labelEn: 'Grapes',                kcal: 69,  protein: 0.7  },
  'диня':                   { label: 'Диня',                      labelEn: 'Watermelon',            kcal: 30,  protein: 0.6  },
  'пъпеш':                  { label: 'Пъпеш',                    labelEn: 'Melon',                 kcal: 34,  protein: 0.8  },
  'ягоди':                  { label: 'Ягоди',                     labelEn: 'Strawberries',          kcal: 32,  protein: 0.7  },
  'малини':                 { label: 'Малини',                    labelEn: 'Raspberries',           kcal: 52,  protein: 1.2  },
  'боровинки':              { label: 'Боровинки',                 labelEn: 'Blueberries',           kcal: 57,  protein: 0.7  },
  'череши':                 { label: 'Череши',                    labelEn: 'Cherries',              kcal: 50,  protein: 1    },
  'праскови':               { label: 'Праскови',                  labelEn: 'Peaches',               kcal: 39,  protein: 0.9  },
  'кайсии':                 { label: 'Кайсии',                    labelEn: 'Apricots',              kcal: 48,  protein: 1.4  },
  'круши':                  { label: 'Круши',                     labelEn: 'Pears',                 kcal: 57,  protein: 0.4  },
  'сливи':                  { label: 'Сливи',                     labelEn: 'Plums',                 kcal: 46,  protein: 0.7  },
  'мандарини':              { label: 'Мандарини',                  labelEn: 'Tangerines',            kcal: 53,  protein: 0.8  },
  'грейпфрут':              { label: 'Грейпфрут',                 labelEn: 'Grapefruit',            kcal: 42,  protein: 0.8  },
  'киви':                   { label: 'Киви',                      labelEn: 'Kiwi',                  kcal: 61,  protein: 1.1  },
  'манго':                  { label: 'Манго',                     labelEn: 'Mango',                 kcal: 60,  protein: 0.8  },
  'ананас':                 { label: 'Ананас',                    labelEn: 'Pineapple',             kcal: 50,  protein: 0.5  },
  'кокос':                  { label: 'Кокос (пресен)',            labelEn: 'Coconut (fresh)',       kcal: 354, protein: 3.3  },
  'смокини':                { label: 'Смокини',                   labelEn: 'Figs',                  kcal: 74,  protein: 0.8  },
  'фурми':                  { label: 'Фурми',                    labelEn: 'Dates',                 kcal: 277, protein: 1.8  },
  'стафиди':                { label: 'Стафиди',                   labelEn: 'Raisins',               kcal: 299, protein: 3.1  },

  // ── Зеленчуци (допълнителни) ───────────────────────────────────
  'спанак':                 { label: 'Спанак',                    labelEn: 'Spinach',               kcal: 23,  protein: 2.9  },
  'тиквички':               { label: 'Тиквички',                  labelEn: 'Zucchini',              kcal: 17,  protein: 1.2  },
  'патладжан':              { label: 'Патладжан',                 labelEn: 'Eggplant',              kcal: 25,  protein: 1    },
  'карфиол':                { label: 'Карфиол',                   labelEn: 'Cauliflower',           kcal: 25,  protein: 1.9  },
  'зеле':                   { label: 'Зеле',                      labelEn: 'Cabbage',               kcal: 25,  protein: 1.3  },
  'лук':                    { label: 'Лук',                       labelEn: 'Onion',                 kcal: 40,  protein: 1.1  },
  'чесън':                  { label: 'Чесън',                     labelEn: 'Garlic',                kcal: 149, protein: 6.4  },
  'гъби':                   { label: 'Гъби',                      labelEn: 'Mushrooms',             kcal: 22,  protein: 3.1  },
  'целина':                 { label: 'Целина',                    labelEn: 'Celery',                kcal: 16,  protein: 0.7  },
  'репички':                { label: 'Репички',                   labelEn: 'Radishes',              kcal: 16,  protein: 0.7  },
  'зелен боб':              { label: 'Зелен боб',                 labelEn: 'Green beans',           kcal: 31,  protein: 1.8  },
  'грах':                   { label: 'Грах',                      labelEn: 'Peas',                  kcal: 81,  protein: 5.4  },
  'царевица':               { label: 'Царевица',                  labelEn: 'Corn',                  kcal: 96,  protein: 3.4  },
  'маслини':                { label: 'Маслини',                   labelEn: 'Olives',                kcal: 145, protein: 1    },
  'кисели краставички':     { label: 'Кисели краставички',         labelEn: 'Pickles',               kcal: 11,  protein: 0.3  },

  // ── Сосове и подправки ─────────────────────────────────────────
  'кетчуп':                 { label: 'Кетчуп',                    labelEn: 'Ketchup',               kcal: 112, protein: 1.7  },
  'майонеза':               { label: 'Майонеза',                  labelEn: 'Mayonnaise',            kcal: 680, protein: 1    },
  'горчица':                { label: 'Горчица',                   labelEn: 'Mustard',               kcal: 66,  protein: 4    },
  'соев сос':               { label: 'Соев сос',                  labelEn: 'Soy sauce',             kcal: 53,  protein: 5    },
  'хумус':                  { label: 'Хумус',                     labelEn: 'Hummus',                kcal: 166, protein: 8    },
  'песто':                  { label: 'Песто',                     labelEn: 'Pesto',                 kcal: 387, protein: 5    },
  'оцет':                   { label: 'Оцет',                      labelEn: 'Vinegar',               kcal: 18,  protein: 0    },
  'балсамов оцет':          { label: 'Балсамов оцет',             labelEn: 'Balsamic vinegar',      kcal: 88,  protein: 0.5  },

  // ── Напитки (безалкохолни) ─────────────────────────────────────
  'кола':                   { label: 'Кока-Кола',                 labelEn: 'Coca-Cola',             kcal: 42,  protein: 0    },
  'кола зиро':              { label: 'Кола Зиро',                 labelEn: 'Cola Zero',             kcal: 0,   protein: 0    },
  'фанта':                  { label: 'Фанта',                     labelEn: 'Fanta',                 kcal: 42,  protein: 0    },
  'спрайт':                 { label: 'Спрайт',                    labelEn: 'Sprite',                kcal: 40,  protein: 0    },
  'портокалов сок':         { label: 'Портокалов сок',            labelEn: 'Orange juice',          kcal: 45,  protein: 0.7  },
  'ябълков сок':            { label: 'Ябълков сок',               labelEn: 'Apple juice',           kcal: 46,  protein: 0.1  },
  'енергийна напитка':      { label: 'Енергийна напитка',         labelEn: 'Energy drink',          kcal: 45,  protein: 0    },
  'кафе':                   { label: 'Кафе (черно)',              labelEn: 'Coffee (black)',        kcal: 2,   protein: 0.1  },
  'капучино':               { label: 'Капучино',                  labelEn: 'Cappuccino',            kcal: 40,  protein: 2    },
  'лате':                   { label: 'Лате',                      labelEn: 'Latte',                 kcal: 50,  protein: 2.5  },
  'чай':                    { label: 'Чай (без захар)',           labelEn: 'Tea (unsweetened)',     kcal: 1,   protein: 0    },
  'захар':                  { label: 'Захар',                     labelEn: 'Sugar',                 kcal: 387, protein: 0    },

  // ── Алкохол ────────────────────────────────────────────────────
  'бира':                   { label: 'Бира',                      labelEn: 'Beer',                  kcal: 43,  protein: 0.5  },
  'бира безалкохолна':      { label: 'Бира безалкохолна',         labelEn: 'Non-alcoholic beer',    kcal: 24,  protein: 0.3  },
  'вино червено':           { label: 'Вино червено',              labelEn: 'Red wine',              kcal: 85,  protein: 0.1  },
  'вино бяло':              { label: 'Вино бяло',                 labelEn: 'White wine',            kcal: 82,  protein: 0.1  },
  'вино розе':              { label: 'Вино розе',                 labelEn: 'Ros\u00e9 wine',        kcal: 83,  protein: 0.1  },
  'шампанско':              { label: 'Шампанско / Просеко',       labelEn: 'Champagne / Prosecco',  kcal: 80,  protein: 0.1  },
  'водка':                  { label: 'Водка',                     labelEn: 'Vodka',                 kcal: 231, protein: 0    },
  'уиски':                  { label: 'Уиски',                     labelEn: 'Whiskey',               kcal: 250, protein: 0    },
  'ром':                    { label: 'Ром',                       labelEn: 'Rum',                   kcal: 231, protein: 0    },
  'джин':                   { label: 'Джин',                      labelEn: 'Gin',                   kcal: 263, protein: 0    },
  'текила':                 { label: 'Текила',                    labelEn: 'Tequila',               kcal: 231, protein: 0    },
  'ракия':                  { label: 'Ракия',                     labelEn: 'Rakia',                 kcal: 231, protein: 0    },
  'мастика':                { label: 'Мастика',                   labelEn: 'Mastika',               kcal: 255, protein: 0    },
  'ликьор':                 { label: 'Ликьор',                    labelEn: 'Liqueur',               kcal: 300, protein: 0    },
  'коктейл мохито':         { label: 'Мохито',                    labelEn: 'Mojito',                kcal: 64,  protein: 0    },
  'коктейл маргарита':      { label: 'Маргарита',                 labelEn: 'Margarita',             kcal: 89,  protein: 0    },

  // ── Готови ястия / полуфабрикати ───────────────────────────────
  'пица маргарита':         { label: 'Пица Маргарита',            labelEn: 'Pizza Margherita',      kcal: 250, protein: 11   },
  'пица пеперони':          { label: 'Пица Пеперони',             labelEn: 'Pizza Pepperoni',       kcal: 280, protein: 13   },
  'кебапче':                { label: 'Кебапче',                   labelEn: 'Kebapche (grilled meat)',kcal: 275, protein: 17, perPiece: true, gramsPerPiece: 80 },
  'кюфте':                  { label: 'Кюфте',                     labelEn: 'Kyufte (meatball)',     kcal: 265, protein: 16, perPiece: true, gramsPerPiece: 80 },
  'шницел':                 { label: 'Шницел',                    labelEn: 'Schnitzel',             kcal: 297, protein: 18   },
  'кренвирш':               { label: 'Кренвирш',                  labelEn: 'Hot dog sausage',       kcal: 290, protein: 11, perPiece: true, gramsPerPiece: 50 },
  'наденица':               { label: 'Наденица',                  labelEn: 'Sausage',               kcal: 320, protein: 14   },
  'луканка':                { label: 'Луканка',                   labelEn: 'Lukanka (dry sausage)', kcal: 438, protein: 24   },
  'суджук':                 { label: 'Суджук',                    labelEn: 'Sudzhuk (dry sausage)', kcal: 455, protein: 22   },
  'салам':                  { label: 'Салам',                     labelEn: 'Salami',                kcal: 336, protein: 22   },
  'шунка':                  { label: 'Шунка',                     labelEn: 'Ham',                   kcal: 145, protein: 21   },
  'пилешка шунка':          { label: 'Пилешка шунка',             labelEn: 'Chicken ham',           kcal: 110, protein: 18   },
  'пуешка шунка':           { label: 'Пуешка шунка',              labelEn: 'Turkey ham',            kcal: 104, protein: 19   },
  'пастърма':               { label: 'Пастърма',                  labelEn: 'Pastrami',              kcal: 195, protein: 30   },

  // ── Тофу и растителни ──────────────────────────────────────────
  'тофу':                   { label: 'Тофу',                      labelEn: 'Tofu',                  kcal: 76,  protein: 8    },
  'темпе':                  { label: 'Темпе',                     labelEn: 'Tempeh',                kcal: 192, protein: 20   },
  'соево мляко':            { label: 'Соево мляко',               labelEn: 'Soy milk',              kcal: 33,  protein: 2.8  },
  'овесено мляко':          { label: 'Овесено мляко',             labelEn: 'Oat milk',              kcal: 43,  protein: 0.4  },
  'бадемово мляко':         { label: 'Бадемово мляко',            labelEn: 'Almond milk',           kcal: 15,  protein: 0.6  },

  // ── Тон консерва и консерви ────────────────────────────────────
  'тон консерва':           { label: 'Тон консерва (в масло)',    labelEn: 'Canned tuna (in oil)',  kcal: 198, protein: 29   },
  'тон консерва вода':      { label: 'Тон консерва (във вода)',   labelEn: 'Canned tuna (in water)',kcal: 116, protein: 26   },
  'сардини консерва':       { label: 'Сардини консерва',          labelEn: 'Canned sardines',       kcal: 208, protein: 25   },
  'скумрия консерва':       { label: 'Скумрия консерва',          labelEn: 'Canned mackerel',       kcal: 205, protein: 19   },
  'боб консерва':           { label: 'Боб консерва',              labelEn: 'Canned beans',          kcal: 94,  protein: 7    },
  'нахут консерва':         { label: 'Нахут консерва',            labelEn: 'Canned chickpeas',      kcal: 119, protein: 7    },
  'царевица консерва':      { label: 'Царевица консерва',         labelEn: 'Canned corn',           kcal: 79,  protein: 2.5  },
}

// Helper: get display label based on lang
export function foodLabel(food, lang) {
  return lang === 'en' ? (food.labelEn || food.label) : food.label
}

export const quickFoods = [
  { key: 'хляб',          grams: 35  },          // Филия хляб
  { key: 'зехтин',        grams: 10  },          // Супена лъжица зехтин
  { key: 'пилешко филе',  grams: 100 },          // 100г пилешко филе
  { key: 'яйце',          grams: 55, count: 1 }, // 1 яйце
]

export const WORKOUT_CATEGORIES = [
  { key: 'Предна верига' },
  { key: 'Задна верига'  },
  { key: 'Бутащи'        },
  { key: 'Дърпащи'       },
  { key: 'Горна част'    },
  { key: 'Крака'         },
  { key: 'Кардио'        },
  { key: 'Цяло тяло'     },
]

// icon field removed — use MUI icons in Sidebar/MobileNav
export const NAV_ITEMS = [
  { view: 'dashboard', labelKey: 'navDashboard' },
  { view: 'food',      labelKey: 'navFood'      },
  { view: 'weight',    labelKey: 'navWeight'    },
  { view: 'ranking',   labelKey: 'navRanking'   },
]
